title: <p align="center"> Bhushan Shivagunde </p>
logo: githubProfile.jpg

description:
  <p align="center">
  <a href="https://github.com/bhushiva/Portfolio/blob/master/Resume_Bhushan_Shivagunde.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/bhushan-shivagunde-b76084209/">LinkedIn</a> |
  <a href="https://github.com/bhushiva">GitHub</a>
  
  
  <br>   
  I'm working on Data Science,  Machine learning & NLP related problems.
  
  <br>
  </p>



theme: jekyll-theme-minimal
