title: <p align="center"> Bhushan Shivagunde </p>
logo: https://github.com/bhushiva/Portfolio/blob/master/githubProfile.jpg

description:
  <p align="center">
  <a href="https://github.com/bhushiva/Portfolio/blob/master/Resume_Bhushan_Shivagunde.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/bhushan-shivagunde-b76084209/">LinkedIn</a> |
  <a href="https://github.com/bhushiva">GitHub</a>
  
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
